// Webhook event type mappings
export const WEBHOOK_EVENT_MAP: { [key: string]: string } = {
	'Appointments Created': 'appointmentsCreated',
	'Appointments Deleted': 'appointmentsDeleted',
	'Appointments Updated': 'appointmentsUpdated',
	'Calls Created': 'callsCreated',
	'Calls Deleted': 'callsDeleted',
	'Calls Updated': 'callsUpdated',
	'Custom Fields Created': 'customFieldsCreated',
	'Custom Fields Deleted': 'customFieldsDeleted',
	'Custom Fields Updated': 'customFieldsUpdated',
	'Deal Custom Fields Created': 'dealCustomFieldsCreated',
	'Deal Custom Fields Deleted': 'dealCustomFieldsDeleted',
	'Deal Custom Fields Updated': 'dealCustomFieldsUpdated',
	'Deals Created': 'dealsCreated',
	'Deals Deleted': 'dealsDeleted',
	'Deals Updated': 'dealsUpdated',
	'Email Events Clicked': 'emEventsClicked',
	'Email Events Opened': 'emEventsOpened',
	'Email Events Unsubscribed': 'emEventsUnsubscribed',
	'Emails Created': 'emailsCreated',
	'Emails Deleted': 'emailsDeleted',
	'Emails Updated': 'emailsUpdated',
	'Events Created': 'eventsCreated',
	'Notes Created': 'notesCreated',
	'Notes Deleted': 'notesDeleted',
	'Notes Updated': 'notesUpdated',
	'People Created': 'peopleCreated',
	'People Deleted': 'peopleDeleted',
	'People Relationship Created': 'peopleRelationshipCreated',
	'People Relationship Deleted': 'peopleRelationshipDeleted',
	'People Relationship Updated': 'peopleRelationshipUpdated',
	'People Stage Updated': 'peopleStageUpdated',
	'People Tags Created': 'peopleTagsCreated',
	'People Updated': 'peopleUpdated',
	'Pipeline Created': 'pipelineCreated',
	'Pipeline Deleted': 'pipelineDeleted',
	'Pipeline Stage Created': 'pipelineStageCreated',
	'Pipeline Stage Deleted': 'pipelineStageDeleted',
	'Pipeline Stage Updated': 'pipelineStageUpdated',
	'Pipeline Updated': 'pipelineUpdated',
	'Reaction Created': 'reactionCreated',
	'Reaction Deleted': 'reactionDeleted',
	'Stage Created': 'stageCreated',
	'Stage Deleted': 'stageDeleted',
	'Stage Updated': 'stageUpdated',
	'Tasks Created': 'tasksCreated',
	'Tasks Deleted': 'tasksDeleted',
	'Tasks Updated': 'tasksUpdated',
	'Text Messages Created': 'textMessagesCreated',
	'Text Messages Deleted': 'textMessagesDeleted',
	'Text Messages Updated': 'textMessagesUpdated',
	'Threaded Reply Created': 'threadedReplyCreated',
	'Threaded Reply Deleted': 'threadedReplyDeleted',
	'Threaded Reply Updated': 'threadedReplyUpdated',
};

// Generate event type options for node properties
export const WEBHOOK_EVENT_OPTIONS = Object.entries(WEBHOOK_EVENT_MAP).map(([name, value]) => ({
	name,
	value,
}));
